### ISSUE TITLE
reslice images to align with Z-axis of B0 field to get around rotation bug in TGV-QSM

### ISSUE THREAD

**Issue by stebo85** [QSMxT/QSMxT#22] opened 2021-07-14 08:40 UTC

**Comment by astewartau** [comment] 2022-07-07 01:41
Seems to be a duplicate of https://github.com/QSMxT/QSMxT/issues/42

**Closed by astewartau** 2022-07-07 01:41 UTC
Labels: bug

**Comment by stebo85** [comment] 2022-07-07 01:45
yes, sorry - I created a duplicate accidently.
